name: Package Extension

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Configure npm
      run: |
        npm config set registry https://registry.npmmirror.com/
        npm config set strict-ssl false
        npm config list
        
    - name: Clean npm cache
      run: npm cache clean --force
        
    - name: Install dependencies
      run: |
        npm install --verbose --no-audit
      
    - name: Install vsce
      run: npm install -g @vscode/vsce
      
    - name: Package Extension
      run: vsce package
      
    - name: Upload Extension Package
      uses: actions/upload-artifact@v4
      with:
        name: extension
        path: "*.vsix"
